name: Docker-Django-Tutorial-CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: "`Up` the docker-compose services"
      run: |
        touch .docker-env
        docker-compose up -d
    - name: Run the test suite
      run: docker-compose run app bash -c "django-admin test --no-input"
    - name: Run the migrations
      run: docker-compose run app bash -c "django-admin migrate --no-input"
